envAlias: development
domainHttp: crud-api.dev.chalam-kitchen.com

crud-api:
  ingress:
    enabled: false

  horizontalPodAutoscaler:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetAverageCPUUtilization: 50

  pods:
    replicas: 1
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 50m
        memory: 30Mi
    env:
      - name: DB_HOST
        value: "postgresql-crud-api"

      - name: DB_NAME
        value: "crud-api"

      - name: DB_USER
        valueFrom:
          secretKeyRef:
            name: crud-api-secret
            key: PGSQL_DEV_USERNAME
            optional: false

      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: crud-api-secret
            key: PGSQL_DEV_PASSWORD
            optional: false

postgresql-crud-api:
  auth:
    secretKeys:
      adminPasswordKey: PGSQL_DEV_PASSWORD
