envAlias: production
domainHttp: crud-api.chalam-kitchen.com

crud-api:
  ingress:
    enabled: false

  horizontalPodAutoscaler:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetAverageCPUUtilization: 50

  pods:
    replicas: 2
    resources:
      limits:
        cpu: 200m
        memory: 100Mi
      requests:
        cpu: 50m
        memory: 30Mi
    env:
      - name: DB_HOST
        value: "postgresql-crud-api"

      - name: DB_NAME
        value: "crud-api"

      - name: DB_USER
        valueFrom:
          secretKeyRef:
            name: crud-api-secret
            key: PGSQL_PROD_USERNAME
            optional: false

      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: crud-api-secret
            key: PGSQL_PROD_PASSWORD
            optional: false

postgresql-crud-api:
  auth:
    secretKeys:
      adminPasswordKey: PGSQL_PROD_PASSWORD
