apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kafka-ing
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP  
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
      - {{ .Values.domainKafka }}
      secretName: kafka-cert
  rules:
    - host: {{ .Values.domainKafka }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kafka-ui
                port:
                  number: 80
