apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: crud-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: crud-api-{{ .Values.envAlias }}
  minReplicas: {{ .Values.crudApiHpaMin }} 
  maxReplicas: {{ .Values.crudApiHpaMax }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
