apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: crud-api-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: crud-api-secret       # name of the k8s Secret to be created
  data:
  - secretKey: PGSQL_DEV_USERNAME
    remoteRef:
      key: initial-secret
      property: PGSQL_DEV_USERNAME

  - secretKey: PGSQL_DEV_PASSWORD
    remoteRef:
      key: initial-secret
      property: PGSQL_DEV_PASSWORD

  - secretKey: PGSQL_PROD_USERNAME
    remoteRef:
      key: initial-secret
      property: PGSQL_PROD_USERNAME

  - secretKey: PGSQL_PROD_PASSWORD
    remoteRef:
      key: initial-secret
      property: PGSQL_PROD_PASSWORD
